// Generated by CoffeeScript 1.8.0
(function() {
  console.log("test");

  chrome.tabs.getSelected(null, function(tab) {
    return alert(tab.title);
  });

}).call(this);

//# sourceMappingURL=popup.js.map
